package main

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"unicode"
)

// A custom sidebar cannot read files, so the installed board is a copy of the source with the
// projects' links written into its data line.
const (
	boardDataPrefix = "const BOARD = "
	boardGenerated  = "// Generated by proj from "
)

type boardLink struct {
	Title string `json:"title"`
	URL   string `json:"url"`
	Icon  string `json:"icon,omitempty"`
}

type boardProject struct {
	Links []boardLink `json:"links"`
}

type boardData struct {
	Projects       map[string]boardProject `json:"projects"`
	BrowserProfile string                  `json:"browserProfile"`
}

func boardDataFor(cfg *config, all []*Manifest) boardData {
	data := boardData{Projects: map[string]boardProject{}, BrowserProfile: cfg.profile}
	for _, m := range all {
		var links []boardLink
		for _, l := range m.Links {
			if l.URL == "" {
				continue
			}
			title := l.Title
			if title == "" {
				title = l.URL
			}
			icon := l.Icon
			if icon == "" {
				icon = defaultLinkIcon(title)
			}
			links = append(links, boardLink{Title: title, URL: l.URL, Icon: icon})
		}
		if len(links) > 0 {
			data.Projects[m.Name] = boardProject{Links: links}
		}
	}
	return data
}

// The icons are SF Symbol names. The first kind with a word in the title wins.
var linkIconKinds = []struct {
	icon  string
	words []string
}{
	{"ticket", []string{"ticket", "issue", "story", "task", "bug", "tracker"}},
	{"arrow.triangle.branch", []string{"pipeline", "build", "ci", "deploy", "release", "merge", "pull", "review", "branch"}},
	{"doc.text", []string{"doc", "docs", "design", "prd", "spec", "rfc", "plan", "notes", "wiki", "requirements"}},
}

// defaultLinkIcon picks a chip icon for a link whose project file names none.
func defaultLinkIcon(title string) string {
	words := strings.FieldsFunc(strings.ToLower(title), func(r rune) bool {
		return !unicode.IsLetter(r) && !unicode.IsDigit(r)
	})
	for _, kind := range linkIconKinds {
		for _, word := range words {
			if slices.Contains(kind.words, word) {
				return kind.icon
			}
		}
	}
	return "link"
}

// renderBoard returns the board source with its data line replaced by data.
func renderBoard(source, sourcePath string, data boardData) (string, error) {
	encoded, err := json.Marshal(data)
	if err != nil {
		return "", err
	}
	lines := strings.Split(source, "\n")
	for i, line := range lines {
		if strings.HasPrefix(line, boardDataPrefix) {
			lines[i] = boardDataPrefix + string(encoded) + ";"
			return boardGenerated + sourcePath + "; edit that file, then run `proj sync`.\n" + strings.Join(lines, "\n"), nil
		}
	}
	return "", fmt.Errorf("%s has no %q line", sourcePath, strings.TrimSpace(boardDataPrefix))
}

func boardInstallPath() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(home, ".config", "cmux", "sidebars", "projects-board.js"), nil
}

// installBoard writes the board with the current projects' links. It replaces a copy or link
// that proj made earlier and refuses to touch anything else at that path.
func installBoard(cfg *config, all []*Manifest) (string, error) {
	src, err := sidebarSource()
	if err != nil {
		return "", err
	}
	source, err := os.ReadFile(src)
	if err != nil {
		return "", err
	}
	rendered, err := renderBoard(string(source), src, boardDataFor(cfg, all))
	if err != nil {
		return "", err
	}
	dst, err := boardInstallPath()
	if err != nil {
		return "", err
	}
	if err := os.MkdirAll(filepath.Dir(dst), 0o755); err != nil {
		return "", err
	}
	info, err := os.Lstat(dst)
	switch {
	case errors.Is(err, os.ErrNotExist):
	case err != nil:
		return "", err
	case info.Mode()&os.ModeSymlink != 0:
		if target, _ := os.Readlink(dst); target != src {
			return "", fmt.Errorf("%s links somewhere else; move it away and rerun", dst)
		}
	default:
		current, err := os.ReadFile(dst)
		if err != nil {
			return "", err
		}
		if !strings.HasPrefix(string(current), boardGenerated) {
			return "", fmt.Errorf("%s already exists and was not written by proj; move it away and rerun", dst)
		}
		if string(current) == rendered {
			return dst, nil
		}
	}
	// Renamed into place so cmux never reloads a half-written file, and so an earlier symlink
	// is replaced instead of written through.
	tmp, err := os.CreateTemp(filepath.Dir(dst), ".projects-board-*")
	if err != nil {
		return "", err
	}
	defer os.Remove(tmp.Name())
	if _, err := tmp.WriteString(rendered); err != nil {
		tmp.Close()
		return "", err
	}
	if err := tmp.Close(); err != nil {
		return "", err
	}
	if err := os.Chmod(tmp.Name(), 0o644); err != nil {
		return "", err
	}
	return dst, os.Rename(tmp.Name(), dst)
}

// refreshBoard keeps an installed board current after a command that may follow an edited
// project file. A board that was never installed stays that way.
func refreshBoard(cfg *config, all []*Manifest) {
	dst, err := boardInstallPath()
	if err != nil {
		return
	}
	if _, err := os.Lstat(dst); err != nil {
		return
	}
	if _, err := installBoard(cfg, all); err != nil {
		fmt.Println("warn  board not refreshed:", err)
	}
}
