import CmuxSidebar
import CmuxSurfaceCatalogModel
import Foundation

/// The custom sidebars' `workspaces[i].agents` without stale sessions and with the agents on
/// `cmux ssh` hosts.
@MainActor
enum WheelhouseRemoteAgents {
    private static var roster = WheelhouseRemoteAgentRoster()
    /// Sessions the app restores at launch are stamped within its first seconds. Read once at
    /// launch, by `WheelhouseAgentsPanel.start`.
    static let restoredBefore = Date().addingTimeInterval(30)

    static func update(_ statuses: [UUID: [UUID: RemoteAgentSidebarStatus]]) {
        roster.update(statuses, now: Date())
    }

    static func merging(_ agents: [CustomSidebarAgentSnapshot], in workspace: Workspace) -> [CustomSidebarAgentSnapshot] {
        let agents = WheelhouseAgentListCleanup.removingStale(agents, restoredBefore: restoredBefore) { pid in
            kill(pid_t(pid), 0) == 0 || errno == EPERM
        }
        let rows = roster.rows(workspaceID: workspace.id)
        guard !rows.isEmpty else { return agents }
        var surfaceIdByPanelId: [UUID: UUID] = [:]
        for paneId in workspace.bonsplitController.allPaneIds {
            for tab in workspace.bonsplitController.tabs(inPane: paneId) {
                guard let panelId = workspace.panelIdFromSurfaceId(tab.id) else { continue }
                surfaceIdByPanelId[panelId] = tab.id.uuid
            }
        }
        let remote = rows.map { row in
            WheelhouseRemoteAgentState(
                panelId: row.panelID, kind: row.kind, name: row.kind == "claude" ? "Claude" : row.kind.capitalized,
                status: row.status, since: row.since)
        }
        return WheelhouseRemoteAgentMerge.merge(agents, remote: remote, surfaceIdByPanelId: surfaceIdByPanelId)
    }
}

/// The Agents panel: a custom sidebar that takes the right sidebar while the selected project
/// has more than one agent, and narrows to a rail when collapsed.
@MainActor
enum WheelhouseAgentsPanel {
    static let panelName = "project-agents"
    static let railName = "project-agents-rail"
    private static let collapsedKey = "wheelhouse.agentsPanel.collapsed"
    private static let enabledKey = "wheelhouse.agentsPanel.enabled"
    private static let generatedHeader =
        "// Generated by Wheelhouse IDE from project-agents.js; changes here are overwritten.\n"

    private static var timer: Timer?
    /// The workspace the open panel was last shown for.
    private static var shownFor: UUID?
    /// Workspaces whose panel the user closed; it stays closed until they are down to one agent.
    private static var dismissed: Set<UUID> = []
    private static var modeBefore: RightSidebarMode = .files
    private static var nameBefore: String?

    static func start() {
        guard timer == nil else { return }
        _ = WheelhouseRemoteAgents.restoredBefore
        installScripts()
        timer = Timer.scheduledTimer(withTimeInterval: 1, repeats: true) { _ in
            MainActor.assumeIsolated { evaluate() }
        }
    }

    /// The right sidebar's width while it shows the rail.
    static func railWidth(_ state: FileExplorerState) -> CGFloat? {
        state.mode == .customSidebar && state.customSidebarName == railName ? 44 : nil
    }

    static func setCollapsed(_ collapsed: Bool) {
        UserDefaults.standard.set(collapsed, forKey: collapsedKey)
        guard let state = AppDelegate.shared?.fileExplorerState, showsPanel(state) else { return }
        state.selectCustomSidebar(name: collapsed ? railName : panelName)
    }

    private static func showsPanel(_ state: FileExplorerState) -> Bool {
        state.isVisible && state.mode == .customSidebar
            && [panelName, railName].contains(state.customSidebarName ?? "")
    }

    private static func evaluate() {
        guard UserDefaults.standard.object(forKey: enabledKey) as? Bool ?? true,
              let app = AppDelegate.shared, let state = app.fileExplorerState,
              let workspace = app.tabManager?.selectedWorkspace else { return }
        let agents = workspace.customSidebarWorkspaceSnapshot(index: 0, selectedId: workspace.id, unreadCount: 0).agents
        let count = WheelhouseAgentsPanelPolicy.agentCount(agents)
        let showing = showsPanel(state)
        if count < 2 {
            dismissed.remove(workspace.id)
        } else if !showing, shownFor == workspace.id {
            dismissed.insert(workspace.id)
        }
        shownFor = showing && count >= 2 ? workspace.id : nil

        switch WheelhouseAgentsPanelPolicy.action(
            agentCount: count, panelShowing: showing, sidebarVisible: state.isVisible,
            dismissed: dismissed.contains(workspace.id)
        ) {
        case .none:
            break
        case .show:
            let mode = state.mode
            let name = state.customSidebarName
            let collapsed = UserDefaults.standard.bool(forKey: collapsedKey)
            // The app's own command: a sidebar shown in another order of steps stays unlaid out.
            guard case .ok = app.applyRightSidebarRemoteCommand(
                .setCustomSidebar(name: collapsed ? railName : panelName, focus: false)
            ) else { return }
            modeBefore = mode == .customSidebar ? modeBefore : mode
            nameBefore = name == panelName || name == railName ? nameBefore : name
            shownFor = workspace.id
        case .hide:
            state.setVisible(false)
            if let nameBefore { state.selectCustomSidebar(name: nameBefore) }
            state.mode = modeBefore
        }
    }

    /// Writes the bundled panel script and its rail copy where custom sidebars are read from,
    /// leaving alone a file of the same name that this app did not write.
    private static func installScripts() {
        guard let source = Bundle.main.resourceURL?.appendingPathComponent("sidebars/\(panelName).js"),
              let script = try? String(contentsOf: source, encoding: .utf8) else { return }
        let directory = CmuxExtensionSidebarSelection.customSidebarsDirectory
        try? FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        let copies = [
            panelName: script,
            railName: script.replacingOccurrences(of: "const RAIL = false;", with: "const RAIL = true;"),
        ]
        for (name, body) in copies {
            let url = directory.appendingPathComponent("\(name).js", isDirectory: false)
            let text = generatedHeader + body
            if let current = try? String(contentsOf: url, encoding: .utf8) {
                guard current.hasPrefix(generatedHeader), current != text else { continue }
            }
            try? text.write(to: url, atomically: true, encoding: .utf8)
        }
    }
}
